# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Pokedex' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pokedex
  pod 'Toaster', '~> 2.3'
  pod 'SDWebImage', '~> 5.11'
  pod 'SwiftLint', '~> 0.43'  
  
  target 'PokedexTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PokedexUITests' do
    # Pods for testing
  end

end
